version: "3.8"

services:
  recetasapi:
    build: .
    container_name: recetasapi
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: 8080
      MONGO_URL: ${MONGO_URL}


