version: "3.8"

services:
  paulacochinaapi:
    build: .
    container_name: paulacochinaapi
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      JWT_SECRET: ${JWT_SECRET}


